### ISSUE TITLE
Auto-completion function does not work

### ISSUE THREAD

**Issue by mynameisfar** [MattFryer/Qlik-Notepad-plus-plus#12]
Hello.
Auto-completion function does not work for me. When I start enter code drop down list do not appear.
Highlighting works correctly.

Notepad++ version 7.5.6

**Comment by MattFryer** [comment]
Hi
Can you confirm if you have enabled auto-completion within the preferences in NP++? By default NP++ doesn't enable it. You can find detail at the bottom of [this page](https://www.qlikviewaddict.com/p/qlikview-notepad.html).

Regards
Matt
