### ISSUE TITLE
functionList.xml already exists in "%UserProfile%\AppData\Roaming\Notepad++"

### ISSUE THREAD

**Issue by Foresco** [MattFryer/Qlik-Notepad-plus-plus#15]
Hello,

I found another functionList.xml (61 KB size) in "%UserProfile%\AppData\Roaming\Notepad++" during installation. So I can't perform step 5 of installation routine.
What should i do in this case?

Thank you

**Comment by MattFryer** [comment]
Hi,
As it says at the end of step 5:

> If prompted to overwrite an existing version of the file, do so.

Regards
Matt

**Comment by Foresco** [comment]
Thank you for your quick answer!

I was confused by the big difference in file sizes.
Is seems working now.

**Comment by MattFryer** [comment]
No problem!

The size difference is due to Notepad++ including more function list support for other languages. I'll update them in the next release.
