### ISSUE TITLE
How to install functionlist.xml in NP++ PortableApps?

### ISSUE THREAD

**Issue by CereS2009** [MattFryer/Qlik-Notepad-plus-plus#8]
i have a NP++ installation via PortableApps, so there is no
**%UserProfile%\AppData\Roaming\Notepad++**
Also i found none in the portable Apps bin folder.
Anybody knows where to copy this file?

It's my first post on GitHub so i hope i'm at the right place. Or should i file it against PortableApps?

**Comment by MattFryer** [comment]
I'm not familiar with PortableApps so can't help I'm afraid. Did you ever work out where to put it?
